import { QuizSessionStatus, type Prisma, type QuizSession } from '@prisma/client';
import type { Database } from '@/database/prisma.client';
import type { AiAssistantService } from './ai-assistant.service';
import type { OptionKey, ParsedQuestion } from '@/utils/quiz-parse';
import { config } from '@/config';

export interface GradeResult {
  /** Correct answers among the gradeable (solved) questions the student answered. */
  score: number;
  /** Gradeable questions — answered AND present in the session AND solved. */
  total: number;
  /** Answered questions present in the session whose correct answer is unknown. */
  unsolved: number;
}

export interface KeyEntry {
  number: number;
  correct: string | null;
}

export interface LeaderboardRow {
  label: string;
  score: number;
  total: number;
}

/**
 * Orchestrates auto-graded revision quizzes. Pure data + AI logic: it never
 * sends Telegram messages itself — the handler/commands own that I/O — which
 * keeps it in the domain layer and trivially unit-testable with a fake AI.
 *
 * A chat has at most one ACTIVE session at a time. Posting questions creates or
 * extends it; it auto-closes after `QUIZ_SESSION_IDLE_HOURS` of silence (or via
 * /endquiz). Correct answers are generated by the AI router and may be overridden
 * by an admin (/setkey).
 */
export class QuizService {
  /** Per-chat promise chain that serialises active-session creation. */
  private readonly chatLocks = new Map<string, Promise<unknown>>();

  constructor(
    private readonly db: Database,
    private readonly ai: AiAssistantService,
  ) {}

  /**
   * Ingest a batch of parsed questions into the chat's active session, then solve
   * them. Returns the question numbers captured (so the handler can confirm).
   */
  async ingestQuestions(dbChatId: string, parsed: ParsedQuestion[]): Promise<number[]> {
    if (parsed.length === 0) return [];
    const session = await this.serialize(dbChatId, () => this.getOrCreateActiveSession(dbChatId));

    // Heartbeat first: bump lastQuestionAt before writing questions so the
    // scheduler's idle auto-close can't fire mid-ingest and orphan them.
    await this.db.quizSession.update({
      where: { id: session.id },
      data: { lastQuestionAt: new Date() },
    });

    await this.db.$transaction(
      parsed.map((q) =>
        this.db.quizQuestion.upsert({
          where: { sessionId_number: { sessionId: session.id, number: q.number } },
          create: {
            sessionId: session.id,
            number: q.number,
            prompt: q.prompt,
            options: q.options as Prisma.InputJsonValue,
          },
          // Keep an existing `correct` (it may be AI-solved or admin-overridden).
          update: { prompt: q.prompt, options: q.options as Prisma.InputJsonValue },
        }),
      ),
    );

    await this.solvePending(session.id);
    return parsed.map((q) => q.number);
  }

  /**
   * Grade a student's submission against the active session. Returns null when no
   * session is active or the answers reference no known questions (so the handler
   * stays silent on unrelated numbered text).
   */
  async gradeSubmission(
    dbChatId: string,
    dbUserId: string,
    answers: Map<number, OptionKey>,
  ): Promise<GradeResult | null> {
    const session = await this.findActiveSession(dbChatId);
    if (!session) return null;

    const numbers = [...answers.keys()];
    let questions = await this.db.quizQuestion.findMany({
      where: { sessionId: session.id, number: { in: numbers } },
    });
    if (questions.length === 0) return null;

    // Solve on demand if the coach's questions hadn't finished solving yet.
    if (questions.some((q) => q.correct === null)) {
      await this.solvePending(session.id);
      questions = await this.db.quizQuestion.findMany({
        where: { sessionId: session.id, number: { in: numbers } },
      });
    }

    let score = 0;
    let total = 0;
    let unsolved = 0;
    for (const q of questions) {
      if (q.correct === null) {
        unsolved++;
        continue;
      }
      total++;
      if (answers.get(q.number) === q.correct) score++;
    }

    await this.db.quizSubmission.create({
      data: {
        sessionId: session.id,
        userId: dbUserId,
        answers: Object.fromEntries([...answers].map(([n, a]) => [String(n), a])),
        score,
        total,
      },
    });

    return { score, total, unsolved };
  }

  /** The active session's answer key, ordered by question number. Null if none active. */
  async answerKey(dbChatId: string): Promise<KeyEntry[] | null> {
    const session = await this.findActiveSession(dbChatId);
    if (!session) return null;
    const questions = await this.db.quizQuestion.findMany({
      where: { sessionId: session.id },
      orderBy: { number: 'asc' },
    });
    return questions.map((q) => ({ number: q.number, correct: q.correct }));
  }

  /**
   * Admin override of correct answers in the active session. Returns count
   * updated, or null. Existing submissions are re-graded against the corrected
   * key so `/quizscores` and `/endquiz` reflect the fix without resubmission.
   */
  async setKey(dbChatId: string, overrides: Map<number, OptionKey>): Promise<number | null> {
    const session = await this.findActiveSession(dbChatId);
    if (!session) return null;
    let updated = 0;
    for (const [number, letter] of overrides) {
      const res = await this.db.quizQuestion.updateMany({
        where: { sessionId: session.id, number },
        data: { correct: letter },
      });
      updated += res.count;
    }
    if (updated > 0) await this.recomputeSubmissions(session.id);
    return updated;
  }

  /** Leaderboard for the active session (most recent submission per user). Null if none active. */
  async scores(dbChatId: string): Promise<LeaderboardRow[] | null> {
    const session = await this.findActiveSession(dbChatId);
    if (!session) return null;
    return this.leaderboard(session.id);
  }

  /** Close the active session and return its final leaderboard. Null if none active. */
  async closeActive(dbChatId: string): Promise<LeaderboardRow[] | null> {
    const session = await this.findActiveSession(dbChatId);
    if (!session) return null;
    await this.db.quizSession.update({
      where: { id: session.id },
      data: { status: QuizSessionStatus.CLOSED, closedAt: new Date() },
    });
    return this.leaderboard(session.id);
  }

  // ── internals ──────────────────────────────────────────────────────────────

  private async leaderboard(sessionId: string): Promise<LeaderboardRow[]> {
    const submissions = await this.db.quizSubmission.findMany({
      where: { sessionId },
      orderBy: { createdAt: 'desc' },
      include: { user: true },
    });
    const latestPerUser = new Map<string, LeaderboardRow>();
    for (const s of submissions) {
      if (latestPerUser.has(s.userId)) continue; // first seen = most recent
      latestPerUser.set(s.userId, { label: userTag(s.user), score: s.score, total: s.total });
    }
    return [...latestPerUser.values()].sort((a, b) => b.score - a.score || a.total - b.total);
  }

  private async findActiveSession(dbChatId: string): Promise<QuizSession | null> {
    return this.db.quizSession.findFirst({
      where: { chatId: dbChatId, status: QuizSessionStatus.ACTIVE },
      orderBy: { startedAt: 'desc' },
    });
  }

  private async getOrCreateActiveSession(dbChatId: string): Promise<QuizSession> {
    const idleMs = config.QUIZ_SESSION_IDLE_HOURS * 3_600_000;
    const active = await this.findActiveSession(dbChatId);
    if (active) {
      if (Date.now() - active.lastQuestionAt.getTime() <= idleMs) return active;
      // Idle too long — close it and open a fresh session for the new batch.
      await this.db.quizSession.update({
        where: { id: active.id },
        data: { status: QuizSessionStatus.CLOSED, closedAt: new Date() },
      });
    }
    return this.db.quizSession.create({ data: { chatId: dbChatId } });
  }

  /**
   * Serialise an operation per chat. Telegraf processes updates concurrently, so
   * two question batches posted at once could otherwise both find "no active
   * session" and each create one, splitting quiz state. Chats are handled by a
   * single process (replicas shard by chat), so an in-process queue is enough.
   */
  private serialize<T>(chatId: string, fn: () => Promise<T>): Promise<T> {
    const prev = this.chatLocks.get(chatId) ?? Promise.resolve();
    const next = prev.then(fn, fn);
    const tail = next.then(
      () => undefined,
      () => undefined,
    );
    this.chatLocks.set(chatId, tail);
    void tail.then(() => {
      if (this.chatLocks.get(chatId) === tail) this.chatLocks.delete(chatId);
    });
    return next;
  }

  /**
   * Solve every still-unsolved question in a session via the AI router. Only
   * persists a letter that is actually one of the question's captured options,
   * so a partially-captured question never gets an impossible key.
   */
  private async solvePending(sessionId: string): Promise<void> {
    const pending = await this.db.quizQuestion.findMany({ where: { sessionId, correct: null } });
    if (pending.length === 0) return;

    const key = await this.ai.solveQuiz(
      pending.map((q) => ({ number: q.number, prompt: q.prompt, options: toOptions(q.options) })),
    );
    if (key.size === 0) return;

    const updates = pending
      .filter((q) => {
        const letter = key.get(q.number);
        return letter !== undefined && letter in toOptions(q.options);
      })
      .map((q) =>
        this.db.quizQuestion.update({
          where: { id: q.id },
          data: { correct: key.get(q.number) },
        }),
      );
    if (updates.length > 0) await this.db.$transaction(updates);
  }

  /** Re-grade every submission in a session against the current answer key. */
  private async recomputeSubmissions(sessionId: string): Promise<void> {
    const [questions, submissions] = await Promise.all([
      this.db.quizQuestion.findMany({ where: { sessionId } }),
      this.db.quizSubmission.findMany({ where: { sessionId } }),
    ]);
    const correctByNumber = new Map<number, string>();
    for (const q of questions) if (q.correct !== null) correctByNumber.set(q.number, q.correct);

    const updates = submissions.map((sub) => {
      let score = 0;
      let total = 0;
      for (const [number, answer] of toAnswerMap(sub.answers)) {
        const correct = correctByNumber.get(number);
        if (correct === undefined) continue; // not in session / still unsolved
        total++;
        if (answer === correct) score++;
      }
      return this.db.quizSubmission.update({ where: { id: sub.id }, data: { score, total } });
    });
    if (updates.length > 0) await this.db.$transaction(updates);
  }
}

/** Build a readable @mention/name for the leaderboard. */
function userTag(u: { username: string | null; firstName: string | null; telegramId: bigint }): string {
  if (u.username) return `@${u.username}`;
  return u.firstName ?? `user ${u.telegramId.toString()}`;
}

/** Coerce a stored Json options blob back into a string map. */
function toOptions(json: Prisma.JsonValue): Record<string, string> {
  if (json && typeof json === 'object' && !Array.isArray(json)) {
    const out: Record<string, string> = {};
    for (const [k, v] of Object.entries(json)) if (typeof v === 'string') out[k] = v;
    return out;
  }
  return {};
}

/** Coerce a stored answers blob ({"31":"D",...}) into a number→letter map. */
function toAnswerMap(json: Prisma.JsonValue): Map<number, string> {
  const map = new Map<number, string>();
  if (json && typeof json === 'object' && !Array.isArray(json)) {
    for (const [k, v] of Object.entries(json)) {
      const n = Number(k);
      if (Number.isInteger(n) && typeof v === 'string') map.set(n, v);
    }
  }
  return map;
}
